In [ ]:
#Q1

# NumPy (Numerical Python) is a Python library used for efficient numerical computations and handling multidimensional arrays.

#It provides fast mathematical operations, linear algebra functions, and support for large datasets.

#NumPy is important in Data Science and Machine Learning because libraries like Pandas, Scikit-learn, and TensorFlow are built on it.

In [ ]:
#Q2

# Python lists can store different data types and are slower for numerical operations, whereas NumPy arrays store homogeneous data and perform computations faster.

# Example of List: L = [1, 2, 3]; Example of Array: A = np.array([1, 2, 3]).

# Adding 2 to each element requires a loop in lists, but in NumPy arrays it is done directly: A + 2 → [3, 4, 5].

In [8]:
#Q3

import numpy as np

# Create a 1D array of numbers from 1 to 10
arr1 = np.arange(1, 11)
print("1D Array:")
print(arr1)

# Create a 3×3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\n3×3 Matrix:")
print(matrix)

# Addition operation
add_result = matrix + 5
print("\nMatrix after Addition (+5):")
print(add_result)

# Multiplication operation
mul_result = matrix * 2
print("\nMatrix after Multiplication (*2):")
print(mul_result)

# Reshaping operation
reshaped_arr = arr1.reshape(2, 5)
print("\nReshaped Array (2×5):")
print(reshaped_arr)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

3×3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix after Addition (+5):
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matrix after Multiplication (*2):
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Reshaped Array (2×5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
#Q4

import numpy as np

# Create NumPy array
marks = np.array([45, 56, 67, 78, 89])

# Mean
mean_value = np.mean(marks)

# Median
median_value = np.median(marks)

# Standard Deviation
std_value = np.std(marks)

# Maximum and Minimum values
max_value = np.max(marks)
min_value = np.min(marks)

# Sort array in ascending order
sorted_marks = np.sort(marks)

# Display results
print("Marks:", marks)
print("Mean =", mean_value)
print("Median =", median_value)
print("Standard Deviation =", std_value)
print("Maximum Value =", max_value)
print("Minimum Value =", min_value)
print("Sorted Array =", sorted_marks)

Marks: [45 56 67 78 89]
Mean = 67.0
Median = 67.0
Standard Deviation = 15.556349186104045
Maximum Value = 89
Minimum Value = 45
Sorted Array = [45 56 67 78 89]


In [1]:
#Q5

import numpy as np

# Create NumPy array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Print first 4 elements
print("First 4 elements:", arr[:4])

# Print alternate elements
print("Alternate elements:", arr[::2])

# Reverse the array
print("Reversed array:", arr[::-1])

# Replace elements greater than 50 with 0
arr[arr > 50] = 0
print("Array after replacement:", arr)

First 4 elements: [10 20 30 40]
Alternate elements: [10 30 50 70]
Reversed array: [80 70 60 50 40 30 20 10]
Array after replacement: [10 20 30 40 50  0  0  0]
